import 'package:flutter/material.dart';
import '../core/app_scope.dart';
import '../core/theme.dart';
import '../widgets/common.dart';
class FeedbackScreen extends StatefulWidget{const FeedbackScreen({super.key});@override State<FeedbackScreen> createState()=>_FeedbackScreenState();}
class _FeedbackScreenState extends State<FeedbackScreen>{int rating=5;String category='General';final comment=TextEditingController();@override Widget build(BuildContext context){final c=AppScope.of(context);final data=c.data!;final avg=data.feedback.isEmpty?0:data.feedback.fold<int>(0,(a,b)=>a+b.rating)/data.feedback.length;final negative=data.feedback.where((e)=>e.rating<=3).toList();final cats=<String,int>{};for(final f in negative){cats[f.category]=(cats[f.category]??0)+1;}final top=cats.entries.isEmpty?null:(cats.entries.toList()..sort((a,b)=>b.value.compareTo(a.value))).first;return ListView(padding:const EdgeInsets.all(24),children:[
 const SectionTitle('Customer Feedback Intelligence',subtitle:'Receipt-linked QR can feed this module; the form below stores feedback locally.'),
 LayoutBuilder(builder:(context,x)=>GridView.count(crossAxisCount:x.maxWidth>800?3:1,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),childAspectRatio:2.4,crossAxisSpacing:12,mainAxisSpacing:12,children:[MetricCard(label:'Average rating',value:'${avg.toStringAsFixed(1)}/5',icon:Icons.star),MetricCard(label:'Responses',value:'${data.feedback.length}',icon:Icons.qr_code),MetricCard(label:'Top issue',value:top?.key??'None',icon:Icons.report_problem_outlined)])),
 const SizedBox(height:18),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[Row(children:[Expanded(child:DropdownButtonFormField<int>(value:rating,items:[1,2,3,4,5].map((e)=>DropdownMenuItem(value:e,child:Text('$e stars'))).toList(),onChanged:(v)=>setState(()=>rating=v??5),decoration:const InputDecoration(labelText:'Rating'))),const SizedBox(width:10),Expanded(child:DropdownButtonFormField<String>(value:category,items:['General','Staff','Waiting time','Pricing','Cleanliness','Availability','Billing'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v)=>setState(()=>category=v??'General'),decoration:const InputDecoration(labelText:'Category')))]),const SizedBox(height:10),TextField(controller:comment,maxLines:2,decoration:const InputDecoration(labelText:'Feedback')),const SizedBox(height:10),Align(alignment:Alignment.centerRight,child:FilledButton(onPressed:() async{await c.addFeedback(rating,category,comment.text.trim());comment.clear();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Feedback stored locally.')));},child:const Text('Save feedback')))]))),
 const SizedBox(height:18),if(top!=null)Card(child:ListTile(leading:const Icon(Icons.lightbulb_outline,color:AppTheme.amber),title:Text('Improvement focus: ${top.key}'),subtitle:Text('${top.value} low-rating feedback items mention this category. Review branch/time patterns before acting.'))),
 ...data.feedback.map((f)=>Card(child:ListTile(leading:CircleAvatar(backgroundColor:f.rating>=4?AppTheme.green:AppTheme.red,child:Text('${f.rating}')),title:Text(f.category),subtitle:Text(f.comment.isEmpty?'No comment':f.comment),trailing:Text('${f.createdAt.day}/${f.createdAt.month}',style:const TextStyle(color:AppTheme.muted)))))
]);}}
